openapi: 3.0.1
info:
  title: Sample
  description: 'Sample API'
  version: '1.0'
paths:
  /messages:
    post:
      summary: Publish Message
      description: Publish Message
      operationId: publish-message
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/publishMessageRequest'
            example:
              message: Hello world!
      responses:
        '201':
          description: 'Successful response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/publishMessageResponse'
              example:
                id: 8599d9e6-24cf-4d65-a79a-9ccb085987df
components:
  schemas:
    publishMessageRequest:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    publishMessageResponse:
      type: object
      properties:
        id:
          type: string
      required:
        - id
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: []
  - apiKeyQuery: []
